<?php declare(strict_types=1);

namespace Lmc\CodingStandard\Integration\Fixtures;

class PhpDoc
{
    // PhpdocToPropertyTypeFixer, PropertyTypeHintSniff
    /** @var int */
    private $integerValue = 3;
    private $undefinedTypeValue = 3;
    /** @var mixed */
    private $undeclaredMixedType;
    /** @var \DateTimeImmutable */
    private $nonScalarType;

    /**
     * Very well documented method.
     * It tests PhpdocAlignFixer, NoSuperfluousPhpdocTagsFixer, PhpdocTrimConsecutiveBlankLineSeparationFixer
     * and possibly other Phpdoc rules.
     *
     *
     *
     * @param   string      $first
     * @throws  \Exception
     * @param   int|float   $second Second parameter does have a comment, unlike the first one.
     * @param   string|null $third Third parameter is optional and has a default value.
     * @return  mixed There is also information about return type.
     */
    public function veryWellDocumented(string $first, int|float $second, ?string $third = '3rd'): mixed
    {
        return $first . $third;
    }

    /**
     * @param int $value
     * @param mixed $mixedType
     * @return bool
     */
    public function methodWithTypesInTypeHints($value, $mixedType)
    {
        return $value > 3 ? true : false;
    }

    /**
     * @param int $intParam
     * @param string $stringParam This phpdoc should be preserved, because it contains some comment for $stringParam.
     * @return void
     */
    public function methodWithMeaningfulParamComment(int $intParam, string $stringParam): void
    {
        // Do nothing.
    }
}
